--- #
sitename: css-nojs
netname: sharp-allen-194ca1
badgeid: 525ccc50-9a15-402a-a948-8a1e4c6b8ea0

collections:
 pages:
  output: true
  permalink: /:slug/
 cards:
  output: true
  permalink: cards/:slug/

lgw_url: http://127.0.0.1:8080
dwl_url: https://dweb.link
pwg_url: https://gateway.ipfs.io
sta_url: https://cdn.statically.io/img

exclude:
 - "*~*"
